Repository nipreps/niworkflows, pull requests merged in 2019-12, with the labels that each got.

#436 ENH: CIFTI / fsLR density
  niworkflows/interfaces/cifti.py
  niworkflows/interfaces/surf.py
Labels: api change

#435 ENH: Add ``n4_only`` workflow -- to skip brain extraction
  niworkflows/anat/ants.py
Labels: new feature

#441 FIX: ``IntraModalMerge`` failed for dims (x, y, z, 1)
  niworkflows/interfaces/images.py
  niworkflows/interfaces/tests/test_images.py
Labels: bug
